version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: dockerfile
    command: --default-authentication-plugin=mysql_native_password
    container_name: apiology-web-container
    depends_on:
      - mysql
    restart: always
    volumes:
      - ./api/:/var/www/html/
    ports:
      - 8090:80
    links:
      - mysql
  mysql:
    image: mysql:5.7
    container_name: apiology-mysql-container
    restart: always
    environment:
      TZ: "America/NewYork"
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: db_name
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
<<<<<<< HEAD
      - 3603:3306
=======
      - 3336:3306
>>>>>>> 202a6a16c0bd8859b8ee0e4be763490be855482a
volumes:
  mysql-data:
