version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: dockerfile
    command: --default-authentication-plugin=mysql_native_password
    container_name: apiology2-web-container
    depends_on:
      - mysql
    restart: always
    volumes:
      - ./api/:/var/www/html/
    ports:
      - 8980:80
    links:
      - mysql
    env_file:
      - ./.env
  mysql:
    image: mysql:5.7
    container_name: apiology2-mysql-container
    restart: always
    environment:
      TZ: "America/NewYork"
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: db_name
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 3603:3306
volumes:
  mysql-data:
